# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4e3e3f2ad7051fa4e907e491999ddfa32d9578f04d7aa385764a14b9588929c7a763f90d642629e90aa331feb53dffeb1239a7e46544738d858bad9129c7535a

test:
  secret_key_base: 2611071f03cdd2cf4d915d0ceb9010be0890faeb78b0ca9cd2fcb55cf036b65d9101d7c132b9a5417cbc97dc65f4cefbbb358e0b3907a6ec99f54c9855bfe9b7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
